[package]
name = "syntastica-macros"
version = "0.3.0"
authors.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
description = "Macros for internal use in syntastica"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
once_cell = "1.17.1"
proc-macro2 = "1.0.58"
quote = "1.0.27"
quote-use = "0.7.1"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
