[package]
name = "syntastica-parsers-git"
version = "0.3.0"
authors.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
description = "Collection of tree-sitter parsers for syntastica, fetching with git in the build-script"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
document-features = { version = "0.2.7", optional = true }
once_cell = "1.17.2"
syntastica-core = { version = "0.3.0", path = "../syntastica-core", default-features = false }
syntastica-macros = { version = "0.3.0", path = "../syntastica-macros" }
syntastica-queries = { version = "0.3.0", path = "../syntastica-queries", optional = true }

[build-dependencies]
cc = "1.0.79"
syntastica-macros = { version = "0.3.0", path = "../syntastica-macros" }
rustc_version = { version = "0.4.0", optional = true }
tree-sitter-wasm-build-tool = { version = "0.2.0", path = "../tree-sitter-wasm-build-tool" }

[package.metadata.docs.rs]
all-features = true

###########################################
### All following code is autogenerated ###
### by running `cargo xtask codegen` in ###
### the syntastica workspace. #############
###########################################

[features]
#! ## Features
default = ["runtime-c", "language-set"]

#! Every supported language has a feature with the same name as the respective public function.
#! Additionally the three feature groups
#! <span class="stab portability"><code>some</code></span>,
#! <span class="stab portability"><code>most</code></span>, and
#! <span class="stab portability"><code>all</code></span>
#! are available.

## Provide an implementation for [`LanguageSet`](syntastica_core::language_set::LanguageSet)
## using pre-compiled [`HighlightConfiguration`](syntastica_core::language_set::HighlightConfiguration)s.
language-set = []
## Provide an implementation for [`LanguageSet`](syntastica_core::language_set::LanguageSet)
## using the query strings from `syntastica-queries`.
raw-language-set = ["dep:syntastica-queries"]

## Include parsers for the most widely known supported languages.
some = [
    "bash",
    "c",
    "cpp",
    "css",
    "go",
    "html",
    "java",
    "javascript",
    "json",
    "lua",
    "python",
    "rust",
    "toml",
    "tsx",
    "typescript",
    "yaml",
]

## Implies <span class="stab portability"><code>some</code></span>.
## Include parsers for most common languages.
most = [
    "some",
    "asm",
    "c_sharp",
    "comment",
    "dart",
    "diff",
    "haskell",
    "jsdoc",
    "json5",
    "jsonc",
    "latex",
    "markdown",
    "markdown_inline",
    "php",
    "regex",
    "ruby",
    "scala",
    "scss",
]

## Implies <span class="stab portability"><code>most</code></span>.
## Include parsers for all supported languages.
all = [
    "most",
    "ebnf",
    "ejs",
    "erb",
    "hexdump",
    "julia",
    "llvm",
    "ocaml",
    "ocaml_interface",
    "ql",
    "rush",
    "verilog",
    "wat",
]

## Use the standard tree-sitter C runtime. See `syntastica`'s
## [WebAssembly support](https://rubixdev.github.io/syntastica/syntastica/#webassembly-support)
## for more information.
runtime-c = ["syntastica-core/runtime-c"]
## Use the pure Rust tree-sitter runtime. See `syntastica`'s
## [WebAssembly support](https://rubixdev.github.io/syntastica/syntastica/#webassembly-support)
## for more information.
runtime-c2rust = ["syntastica-core/runtime-c2rust"]

## Meant to be enabled when building docs
docs = ["dep:document-features", "dep:rustc_version"]

asm = []
bash = []
c = []
c_sharp = []
comment = []
cpp = []
css = []
dart = []
diff = []
ebnf = []
ejs = []
erb = []
go = []
haskell = []
hexdump = []
html = []
java = []
javascript = []
jsdoc = []
json = []
json5 = []
jsonc = []
julia = []
latex = []
llvm = []
lua = []
markdown = []
markdown_inline = []
ocaml = []
ocaml_interface = []
php = []
python = []
ql = []
regex = []
ruby = []
rush = []
rust = []
scala = []
scss = []
toml = []
tsx = []
typescript = []
verilog = []
wat = []
yaml = []
